P_aleatoria = [
    "computadora",
    "elefante",
    "jardin",
    "hamburguesa",
    "girasol",
    "escritorio",
    "pintura",
    "biblioteca",
    "experiencia",
    "telescopio",
    "helicoptero",
    "catarata",
    "montana",
    "cine",
    "guitarra",
    "paraguas",
    "chocolate",
    "dinosaurio",
    "mariposa",
    "ventana",
    "camara",
    "zanahoria",
    "astronomia",
    "espagueti"
] #BANCO DE PALABRAS